[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "npm"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install --no-optional --ignore-scripts --no-fund --no-audit"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run predeploy && npm run start"

[variables]
NODE_ENV = "production" 