[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "9000"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 