[build]
skipBuild = false

[deploy]
startCommand = "cd .medusa/server && npm install --no-fund --no-audit && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "9000"
NPM_CONFIG_LEGACY_PEER_DEPS = "true" 