[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "sh start-medusa.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "9000"
DATABASE_TYPE = "postgres"
MEDUSA_FF_PRODUCT_CATEGORIES = "true"
NPM_CONFIG_OPTIONAL = "false"
NPM_CONFIG_PLATFORM = "linux"
NPM_CONFIG_ARCH = "x64"
NPM_CONFIG_ENGINE_STRICT = "false"
NPM_CONFIG_IGNORE_SCRIPTS = "false" 