[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "npm"]

[build.nixpacksPlan.phases.install]
cmds = ["npm install --no-optional --ignore-scripts --no-fund --no-audit"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "cd .medusa/server && npm install && npm run predeploy && npm run start"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
PORT = "9000"
NPM_CONFIG_OPTIONAL = "false"
NPM_CONFIG_PLATFORM = "linux"
NPM_CONFIG_ARCH = "x64"
NPM_CONFIG_ENGINE_STRICT = "false"
NPM_CONFIG_IGNORE_SCRIPTS = "true" 